<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Conclusion - Testing the Effectiveness of Common Deletion Methods and Data Recoverability Post-Deletion</title>
    <link rel="stylesheet" href="../assets/style.css">  
</head>
<body>
    <?php include '../includes/navbar.php'; ?>
    <div class="content-wrapper">
        <?php include '../includes/header.php'; ?>
        <div class="main-content">
            <h2>Results Explained</h2>
            <h3>Built in GUI Windows 11 Tools (Recycle Bin, Disk Management)</h3>
                <p>Recycle Bin and Disk Management - Quick Format revealed significant limitations in Windows’ default deletion methods. Both emptying the Windows Recycle Bin and performing a Quick Format via Disk Management failed to securely remove the test data from the HDD. This finding aligns with the work of Garfinkel and Shelat (2003), confirming that these convenient methods are susceptible to forensic recovery. These methods did not erase the data but instead marked the sectors utilised by the test data as available, with Disk Management only changing the data of the File System. The deletion process utilised by both methods meant that the underlying data remained intact on the disk until overwritten by new data, rendering the data recoverable through forensic techniques.   </p>
                <p>Whilst both these tools are the most easily accessible to users, being integrated directly into the Windows operating system by default, their convenience comes at the cost of security. Although they were the fastest methods tested, taking less than a second, they are useful for routine file management, yet they do not guarantee secure removal of data. Across all file systems tested, the data was recoverable using all three forensic recovery tools. Thus, highlighting the critical gap in user understanding, with many users believing emptying the Recycle Bin or performing a disk format is sufficient for data deletion, when these methods leave data prone to forensic recovery.</p>
            <img src="../pictures/recyclebindeletion.png" alt="Recycle Bin Deletion" width="600">
            <br>
            <img src="../pictures/diskmanagementdeletion.png" alt="Disk Management Deletion" width="600">
                <p>Microsoft could provide more clarity to end users regarding deleted data being recoverable. Although Microsoft does provide a secure deletion method through Diskpart, this isn’t overtly obvious as a solution for secure deletion, nor are instructions clearly provided as to how it works within the Windows 11 environment. Diskpart is accessible through a command line interface (CLI) and not a graphical user interface (GUI) like the Recycle Bin and Disk Management, of which make the deletion process more seamless for users. Despite this, Windows methods fail to provide users information on how the data is being deleted.  Specialised secure deletion software not only provides users the opportunity to decide which overwriting algorithm to utilise but informs the user on how many times the algorithm is performed in passes. By implementing a form of this within a standardised environment such as Windows 11, users would be more informed about secure deletion practices.</p>
            <h3>Windows Diskpart - Clean All</h3>
                <p>The Windows DiskPart "clean all" command successfully preventing all three forensic recovery tools from recovering the test data. This process worked at a low level, bypassing file systems to directly overwrite disk sectors. Thus, achieving secure deletion across the entire drive performing similarly to British HMG IS5 baseline, but across the entire HDD. While effective, this approach was the most time consuming taking three hours to complete. The thoroughness in utilising the “clean all” command comes at the expense of speed, as it must write to every single sector on the drive, differing from the secure deletion tools that allow users to select partition and single file or folder secure overwriting. This makes "clean all" significantly slower than the alternative methods tested, but far more secure for total data removal on a HDD. Thus, making it suitable for users requiring total data erasure when preparing a HDD for disposal or resale.</p>
                <p>Despite its effectiveness, Windows provides minimal documentation about this utility within the Windows 11 environment. The only built-in reference is the brief description available through the command-line “help” function. The lack of documentation makes accessibility more difficult for non-technical users who might benefit from secure deletion capabilities but lack the experience to navigate a command line interface (CLI). DiskPart presents inherent difficulties for inexperienced users. With no visual feedback in a graphical user interface (GUI) or intuitive controls, mistakes could occur presenting serious consequences, such as accidentally wiping the wrong drive. The "clean all" command offers no progress indicators, confirmation prompts, or safeguards. With these factors, unintentional deletion could occur, potentially violating GDPR Article 5 1(f).</p>
                <p>Microsoft could significantly improve this method of deletion by the functionality of the “clean all” command into the GUI-based Disk Management tool. A secure erase option during formatting would make this feature more accessible to all users. Additionally, Windows could benefit from clearer documentation within the operating system itself, perhaps through documentation or contextual tooltips that explain the differences between standard and secure deletion methods. Such improvements would help bridge the gap between technical data security requirements and real-world usability.</p>
            <img src="../pictures/diskpart.png" alt="Disk Management Deletion" width="600">
            <h3>Specalised Software Secure Deletion Tools</h3>
            <h4>Eraser</h4>
                <p>The third-party secure deletion tools proved varying levels of effectiveness and usability during testing. Eraser emerged as the most capable solution, combining a modern interface with flexible options. Eraser successfully preventing forensic recovery against the test files using both its default Pseudorandom algorithm and the British HMG IS5 standard. Pseudorandom data worked with no issue, replacing each sector in the partition with random data. The British HMG IS5 Baseline method wrote zeros over each sector within the partition. The Eraser Website provides information on each overwriting algorithm, as well as a clear instructions. Eraser completed each algorithm across the different file systems in a consistent thirteen seconds. However, it is important to note that a larger partition or file size than 500MB (or more passes) would take significantly longer, similarly to Diskpart “clean all”. Despite this, the customisability of the application allows for selected data or partitions to be erased, rather than the entire drive. Eraser provided the best GUI experience, with a modern looking and informative display. The customisability in both selection of data and overwriting algorithms far exceeded what File Shredder or WipeFile provided, balancing both the speed of the alternative methods, with the thoroughness of the “clean all” command. </p>
                <b>Eraser is the recommended solution for users requiring secure data deletion, providing adequate data deletion, with extensive documentation and an easy-to-navigate GUI.</b>
            <br>
            <br>
            <img src="/pictures/eraser.png" alt="Demonstration of the Eraser GUI" width="600">
            <h4>File Shredder</h4>
                <p>File Shredder, the oldest tool tested with its website dating 2007. provided a dated but functional GUI reminiscent of the file explorer from Windows XP, as can be seen below. Despite its older looking interface compared to Eraser and WipeFile, it was clear in its navigation with easily distinguishable option, suggesting that interface age does not compromise usability. </p>
                <p>File Shredder's approach differed fundamentally from comprehensive tools like Eraser. Rather than sanitising entire partitions, File Shredder only overwrote the specific sectors containing deleted files, leaving residual system data and volume information intact across all tested file systems. This was the same for both the secure erasing algorithm and the default DoD 5220-22.M algorithm. This selective overwrite process overwrote the test files into randomised data whilst not touching surrounding partition structures. Thus, leaving potentially recoverable metadata. However, across the three forensic recovery tools no test data could be found within this.</p> 
            <img src="/pictures/fileshredder.png" alt="Demonstration of the Eraser GUI" width="600">
            <h4>WipeFile</h4>
                <p>Lastly, WipeFile was tested. The GUI was simple, but easy to navigate. Both overwriting algorithms generated errors, shown below. Administrator privileges were granted so the origin of this error is unknown. The default settings of Simple Deletion were unsuccessful at securely removing the data and operated similarly to the Windows Recycle Bin. The NATO Standard Deletion method was successful at securely removing the data through overwriting each file with random data, however leaving residue file system metadata. Despite the error, this algorithm was effective.</p>
                <p>The WipeFile simple method failed to remove the test data, marking the sectors of the test data as available for use but not removing the data. This method performed the same as the Recycle Bin and therefore cannot be recommended as a solution for secure data deletion. </p>
            <img src="/pictures/wipefile.png" alt="Demonstration of the Eraser GUI" width="600">
            <h4>Physical Destruction</h4>
                <p>Physical Destruction, as expected was successful in rendering the test HDD inoperable, thus making the test data inaccessible through the three forensic software tools used. The HDD was dropped from a significant height (five meters) within a closed environment. After retrieving the HDD and attempting to connect the drive back to the test environment, the drive failed to connect, as the drive was rendered inoperable. </p>
                <p>This was the most destructive method, and whilst it was successful at rendering the test files unrecoverable, there is the potential for it to be repaired, due to the method of physical destruction used in this project. Physical Destruction should only be used as a deletion method if necessary to render data irrecoverable and a more effective method should be used. Shredding through a reputable data disposal company, such as Shred-it UK, would ensure data is fully irreparable beyond repair. However, less wasteful alternatives exist and should be considered before physical destruction if not required, as per GDPR. Specialised secure deletion software can ensure data irreversibly, whilst allowing for the storage device to be repurposed.</p>
            <h2> Conclusion</h2>
                <p>This study evaluated common deletion methods on HDDs, revealing critical gaps between user misconceptions and technical realities. Built-in Windows tools (Recycle Bin, Quick Format) only left sectors containing data unallocated, making it recoverable via forensic tools. Secure methods such as Eraser’s British HMG IS5 algorithm and Diskpart’s "clean all" ensured irreversibility. Physical destruction was effective but impractical for most users. The project identifies the need for improved default deletion practices in Windows 11 and better information for users on secure deletion practices. Future projects should expand testing to SSDs and cloud storage, addressing modern storage challenges. In addition, the design of a new secure deletion tool could be considered to compete with modern requirements. This project provides actionable insights for enhancing data privacy practices in personal and professional settings.</p>
                <b>Please see Additional Resources for further resources and link to Eraser, the recommended option for secure data deletion</b>
        </div>
    </div>
    <script src="../assets/script.js"></script>
</body>
</html>